# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sim_control.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sim_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sim_control.proto\x12\x07psc.sim\"2\n\x11SetPresentRequest\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\x0f\n\x07present\x18\x02 \x01(\x08\"\x14\n\x12SetPresentResponse2S\n\nSimControl\x12\x45\n\nSetPresent\x12\x1a.psc.sim.SetPresentRequest\x1a\x1b.psc.sim.SetPresentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETPRESENTREQUEST']._serialized_start=30
  _globals['_SETPRESENTREQUEST']._serialized_end=80
  _globals['_SETPRESENTRESPONSE']._serialized_start=82
  _globals['_SETPRESENTRESPONSE']._serialized_end=102
  _globals['_SIMCONTROL']._serialized_start=104
  _globals['_SIMCONTROL']._serialized_end=187
# @@protoc_insertion_point(module_scope)
